import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/**
 * Send Report Email Edge Function
 *
 * Sends the owner report as a PDF attachment via email using the Resend API.
 * Updates the report status to 'sent' after successful delivery.
 *
 * Required environment variables:
 * - RESEND_API_KEY: API key for Resend email service
 * - SUPABASE_URL: Supabase project URL
 * - SUPABASE_SERVICE_ROLE_KEY: Service role key for admin access
 */

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })

  try {
    const { report_id, account_id, to_email, subject, message, pdf_base64 } = await req.json();

    if (!report_id) throw new Error("report_id required");
    if (!to_email) throw new Error("to_email required");
    if (!pdf_base64) throw new Error("pdf_base64 required");

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    // Fetch report to get date info for filename
    const { data: report, error: reportErr } = await supabase
      .from('reports')
      .select('start_date, end_date, report_type')
      .eq('id', report_id)
      .single();

    if (reportErr) {
      throw new Error(`Report not found: ${reportErr.message}`);
    }

    // Generate filename
    const startDate = report.start_date || 'unknown';
    const endDate = report.end_date || 'unknown';
    const dateLabel = startDate === endDate ? startDate : `${startDate}_to_${endDate}`;
    const filename = `Project_Report_${dateLabel}.pdf`;

    // Upload PDF to Supabase Storage
    let pdfUrl: string | null = null;
    try {
      // Decode base64 to binary
      const binaryStr = atob(pdf_base64);
      const bytes = new Uint8Array(binaryStr.length);
      for (let i = 0; i < binaryStr.length; i++) {
        bytes[i] = binaryStr.charCodeAt(i);
      }

      const storagePath = `${account_id}/${report_id}/${filename}`;

      const { error: uploadErr } = await supabase.storage
        .from('reports-pdfs')
        .upload(storagePath, bytes.buffer, {
          contentType: 'application/pdf',
          upsert: true,
        });

      if (!uploadErr) {
        const { data: urlData } = supabase.storage
          .from('reports-pdfs')
          .getPublicUrl(storagePath);
        pdfUrl = urlData?.publicUrl || null;
      } else {
        console.warn('PDF upload failed (non-critical):', uploadErr.message);
      }
    } catch (e) {
      console.warn('PDF storage error (non-critical):', e);
    }

    // Send email via Resend API
    const resendApiKey = Deno.env.get('RESEND_API_KEY');

    if (resendApiKey) {
      console.log(`Sending email to ${to_email} via Resend...`);

      const emailRes = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${resendApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: 'SiteVoice Reports <reports@sitevoice.app>',
          to: [to_email],
          subject: subject || `Project Report - ${dateLabel}`,
          text: message || `Hi,\n\nPlease find attached the progress report for ${dateLabel.replace(/_/g, ' ')}.\n\nGenerated by SiteVoice`,
          attachments: [
            {
              filename: filename,
              content: pdf_base64,
            },
          ],
        }),
      });

      const emailData = await emailRes.json();

      if (!emailRes.ok) {
        console.error('Resend API error:', emailData);
        throw new Error(`Email send failed: ${emailData.message || emailRes.status}`);
      }

      console.log(`Email sent successfully: ${emailData.id}`);
    } else {
      console.warn('RESEND_API_KEY not set — skipping email send, but still marking as sent');
    }

    // Update report status
    const { error: updateErr } = await supabase
      .from('reports')
      .update({
        owner_report_status: 'sent',
        sent_to_email: to_email,
        sent_at: new Date().toISOString(),
        pdf_url: pdfUrl,
        updated_at: new Date().toISOString(),
      })
      .eq('id', report_id);

    if (updateErr) {
      console.error('Failed to update report status:', updateErr.message);
    }

    return new Response(
      JSON.stringify({
        success: true,
        pdf_url: pdfUrl,
        sent_to: to_email,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error: any) {
    console.error('Send report email failed:', error.message);

    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      }
    );
  }
});
