-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_name text NOT NULL,
  admin_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  transcription_provider text DEFAULT 'groq'::text CHECK (transcription_provider = ANY (ARRAY['groq'::text, 'openai'::text, 'gemini'::text])),
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.users(id)
);
CREATE TABLE public.action_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  voice_note_id uuid,
  category text NOT NULL CHECK (category = ANY (ARRAY['update'::text, 'approval'::text, 'action_required'::text])),
  summary text NOT NULL,
  priority USER-DEFINED DEFAULT 'Med'::priority_level,
  manager_approval boolean DEFAULT false,
  project_id uuid NOT NULL,
  account_id uuid NOT NULL,
  user_id uuid,
  assigned_to uuid,
  details text,
  ai_analysis text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'in_progress'::text, 'verifying'::text, 'completed'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  due_date timestamp with time zone,
  proof_photo_url text,
  parent_action_id uuid,
  is_dependency_locked boolean DEFAULT false,
  interaction_history jsonb DEFAULT '[]'::jsonb,
  is_directive boolean DEFAULT false,
  acknowledged_at timestamp with time zone,
  acknowledged_by uuid,
  requires_proof boolean DEFAULT false,
  delegation_voice_note_id uuid,
  CONSTRAINT action_items_pkey PRIMARY KEY (id),
  CONSTRAINT action_items_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT action_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT action_items_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT action_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT action_items_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT action_items_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT action_items_parent_action_id_fkey FOREIGN KEY (parent_action_id) REFERENCES public.action_items(id),
  CONSTRAINT action_items_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.users(id),
  CONSTRAINT action_items_delegation_voice_note_id_fkey FOREIGN KEY (delegation_voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.ai_prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['groq'::text, 'openai'::text, 'gemini'::text])),
  purpose text NOT NULL,
  version integer NOT NULL,
  prompt text NOT NULL,
  output_schema jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT ai_prompts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.design_change_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  account_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  before_spec text,
  after_spec text,
  reason text,
  requested_by uuid NOT NULL,
  approved_by uuid,
  status text DEFAULT 'proposed'::text CHECK (status = ANY (ARRAY['proposed'::text, 'approved'::text, 'rejected'::text, 'implemented'::text])),
  voice_note_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT design_change_logs_pkey PRIMARY KEY (id),
  CONSTRAINT design_change_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT design_change_logs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT design_change_logs_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT design_change_logs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT design_change_logs_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.finance_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  account_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['purchase'::text, 'labour_payment'::text, 'petty_cash'::text, 'other'::text])),
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  item text,
  unit_price numeric,
  quantity numeric,
  unit text,
  vendor text,
  description text,
  voice_note_id uuid,
  action_item_id uuid,
  recorded_by uuid,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT finance_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT finance_transactions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT finance_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT finance_transactions_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT finance_transactions_action_item_id_fkey FOREIGN KEY (action_item_id) REFERENCES public.action_items(id),
  CONSTRAINT finance_transactions_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id),
  CONSTRAINT finance_transactions_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.material_specs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  account_id uuid NOT NULL,
  category text,
  material_name text NOT NULL,
  brand text,
  specification text,
  unit_price numeric,
  unit text,
  quantity numeric,
  vendor text,
  status text DEFAULT 'planned'::text CHECK (status = ANY (ARRAY['planned'::text, 'ordered'::text, 'delivered'::text, 'installed'::text])),
  voice_note_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT material_specs_pkey PRIMARY KEY (id),
  CONSTRAINT material_specs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT material_specs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT material_specs_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  account_id uuid NOT NULL,
  project_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['action_forwarded'::text, 'action_instructed'::text, 'proof_requested'::text, 'proof_uploaded'::text, 'status_changed'::text, 'owner_approval_response'::text, 'escalated_to_owner'::text, 'note_added'::text])),
  title text NOT NULL,
  body text,
  reference_id uuid,
  reference_type text CHECK (reference_type = ANY (ARRAY['action_item'::text, 'owner_approval'::text, 'voice_note'::text])),
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.owner_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  account_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  owner_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  amount numeric,
  currency text DEFAULT 'INR'::text,
  category text NOT NULL CHECK (category = ANY (ARRAY['spending'::text, 'design_change'::text, 'material_change'::text, 'schedule_change'::text, 'other'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'deferred'::text])),
  voice_note_id uuid,
  action_item_id uuid,
  owner_response text,
  responded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT owner_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT owner_approvals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT owner_approvals_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT owner_approvals_action_item_id_fkey FOREIGN KEY (action_item_id) REFERENCES public.action_items(id),
  CONSTRAINT owner_approvals_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT owner_approvals_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT owner_approvals_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_owners_pkey PRIMARY KEY (id),
  CONSTRAINT project_owners_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_owners_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  location text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  account_id uuid NOT NULL,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  account_id uuid,
  CONSTRAINT roles_pkey PRIMARY KEY (id),
  CONSTRAINT roles_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.super_admins (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT super_admins_pkey PRIMARY KEY (id),
  CONSTRAINT super_admins_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role text NOT NULL,
  phone_number text,
  current_project_id uuid,
  account_id uuid NOT NULL,
  email text,
  preferred_language text DEFAULT 'en'::text,
  reports_to uuid,
  department text,
  full_name text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_current_project_id_fkey FOREIGN KEY (current_project_id) REFERENCES public.projects(id),
  CONSTRAINT users_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT users_reports_to_fkey FOREIGN KEY (reports_to) REFERENCES public.users(id)
);
CREATE TABLE public.voice_note_ai_analysis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voice_note_id uuid,
  source_transcript text CHECK (source_transcript = ANY (ARRAY['original'::text, 'edited'::text])),
  edit_version integer,
  intent text CHECK (intent = ANY (ARRAY['update'::text, 'approval'::text, 'action_required'::text, 'information'::text])),
  priority text CHECK (priority = ANY (ARRAY['Low'::text, 'Med'::text, 'High'::text, 'Critical'::text])),
  short_summary text NOT NULL,
  detailed_summary text,
  confidence_score numeric,
  ai_model text,
  prompt_version text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT voice_note_ai_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_ai_analysis_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.voice_note_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voice_note_id uuid,
  approval_type text,
  amount numeric,
  currency text DEFAULT 'INR'::text,
  due_date date,
  requires_manager boolean,
  confidence_score numeric,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT voice_note_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_approvals_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.voice_note_edits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voice_note_id uuid,
  edit_number integer NOT NULL,
  before_text text NOT NULL,
  after_text text NOT NULL,
  edited_by uuid,
  edit_reason text CHECK (edit_reason = ANY (ARRAY['typo'::text, 'translation_fix'::text, 'clarification'::text, 'other'::text])),
  edited_at timestamp without time zone DEFAULT now(),
  CONSTRAINT voice_note_edits_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_edits_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT voice_note_edits_edited_by_fkey FOREIGN KEY (edited_by) REFERENCES public.users(id)
);
CREATE TABLE public.voice_note_forwards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_note_id uuid,
  forwarded_note_id uuid,
  forwarded_from uuid,
  forwarded_to uuid,
  instruction_note_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  forward_note text,
  CONSTRAINT voice_note_forwards_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_forwards_original_note_id_fkey FOREIGN KEY (original_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT voice_note_forwards_forwarded_note_id_fkey FOREIGN KEY (forwarded_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT voice_note_forwards_forwarded_from_fkey FOREIGN KEY (forwarded_from) REFERENCES public.users(id),
  CONSTRAINT voice_note_forwards_forwarded_to_fkey FOREIGN KEY (forwarded_to) REFERENCES public.users(id),
  CONSTRAINT voice_note_forwards_instruction_note_id_fkey FOREIGN KEY (instruction_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.voice_note_labor_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voice_note_id uuid,
  labor_type text,
  headcount integer,
  duration_days integer,
  start_date date,
  urgency text CHECK (urgency = ANY (ARRAY['normal'::text, 'urgent'::text])),
  confidence_score numeric,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT voice_note_labor_requests_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_labor_requests_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.voice_note_material_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voice_note_id uuid,
  material_category text,
  material_name text,
  quantity numeric,
  unit text,
  brand_preference text,
  delivery_date date,
  urgency text CHECK (urgency = ANY (ARRAY['normal'::text, 'urgent'::text])),
  extracted_from text CHECK (extracted_from = ANY (ARRAY['explicit'::text, 'implicit'::text])),
  confidence_score numeric,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT voice_note_material_requests_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_material_requests_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id)
);
CREATE TABLE public.voice_note_project_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voice_note_id uuid,
  event_type text CHECK (event_type = ANY (ARRAY['project_update'::text, 'issue_reported'::text, 'approval_request'::text, 'instruction'::text, 'information'::text])),
  title text NOT NULL,
  description text,
  requires_followup boolean DEFAULT false,
  suggested_due_date date,
  suggested_assignee uuid,
  confidence_score numeric,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT voice_note_project_events_pkey PRIMARY KEY (id),
  CONSTRAINT voice_note_project_events_voice_note_id_fkey FOREIGN KEY (voice_note_id) REFERENCES public.voice_notes(id),
  CONSTRAINT voice_note_project_events_suggested_assignee_fkey FOREIGN KEY (suggested_assignee) REFERENCES public.users(id)
);
CREATE TABLE public.voice_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  project_id uuid NOT NULL,
  audio_url text NOT NULL,
  transcript_raw text,
  processed_json jsonb,
  status USER-DEFINED DEFAULT 'processing'::voice_note_status,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  account_id uuid NOT NULL,
  parent_id uuid,
  recipient_id uuid,
  transcription text,
  detected_language text,
  translated_transcription jsonb,
  category USER-DEFINED,
  transcript_final text,
  is_edited boolean DEFAULT false,
  detected_language_code text,
  edit_history jsonb DEFAULT '[]'::jsonb,
  transcript_raw_original text,
  transcript_en_original text,
  transcript_raw_current text,
  transcript_en_current text,
  asr_confidence numeric,
  transcription_locked boolean DEFAULT false,
  last_edited_by uuid,
  last_edited_at timestamp without time zone,
  validation_status text DEFAULT 'pending_validation'::text CHECK (validation_status = ANY (ARRAY['pending_validation'::text, 'validated'::text, 'rejected'::text])),
  ai_suggested_summary text,
  ai_suggested_category text,
  worker_confirmed_at timestamp with time zone,
  worker_edited_summary text,
  CONSTRAINT voice_notes_pkey PRIMARY KEY (id),
  CONSTRAINT voice_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT voice_notes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT voice_notes_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT voice_notes_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.voice_notes(id),
  CONSTRAINT voice_notes_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id),
  CONSTRAINT voice_notes_last_edited_by_fkey FOREIGN KEY (last_edited_by) REFERENCES public.users(id)
);